In [2]:
run play_train_eval_zero.py \
--agent bots/zero_test.hdf5 \
-g 1000 \
-d /Users/georgeyeh/DLGo/bots \
-w 1 \
-b 9 \
--lr 0.01 \
--bs 1024 \
-l zerolog

Reference: bots/zero_test.hdf5

Waiting for workers...


KeyboardInterrupt: 

In [1]:
run zero_demo.py

/Users/georgeyeh/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


Starting the game!
Starting the game!
Starting the game!
Starting the game!
Starting the game!
Epoch 1/1
503/503 [==============================] - 1s 1ms/step - loss: 5.4029 - dense_1_loss: 4.4056 - dense_3_loss: 0.9973


In [ ]:
"""
python init_zero_agent.py \
--board-size 9 \
bots/zero_test1.hdf5

python play_train_eval_zero.py \
--agent bots/zero_agent_00001300.hdf5 \
-g 100 \
-d /Users/georgeyeh/DLGo/bots \
-w 1 \
-b 9 \
--lr 0.01 \
--bs 100 \
-l zerov2log
"""

In [ ]:
"""
python init_zero_agent.py \
--board-size 9 \
bots/zerov2_test.hdf5

python init_zero_agent_with_reg.py \
--board-size 9 \
bots/zerov3_test.hdf5

python play_train_eval_zero.py \
--agent bots/zero_agent_cur.hdf5 \
-g 200 \
-d /home/ubuntu/DLGo/bots \
-w 1 \
-b 9 \
--lr 0.01 \
--bs 200 \
-l zerolog

python play_train_eval_zero.py \
--agent bots/zero_agent_cur.hdf5 \
-g 500 \
-d /home/ubuntu/DLGo/bots \
-w 1 \
-b 9 \
--lr 0.01 \
--bs 100 \
-l zerolog

python play_train_eval_zero.py \
--lagent bots/zero_agent_cur.hdf5 \
--ragent bots/zero_agent_v4.hdf5 \
-g 50 \
-d /home/ubuntu/git/AlphaGo-Zero-Compact/DLGo/bots \
-w 1 \
-b 9 \
--lr 0.01 \
--bs 256 \
-l log

devices = tf.config.list_logical_devices()
_LOCAL_DEVICES = [x.name for x in devices]

pip install npm

sudo npm install forever -g

python web_demo.py \
--bind-address 0.0.0.0 \
--port 5000

http://ec2-3-19-61-177.us-east-2.compute.amazonaws.com:5000/static/play_zero_99.html

forever start -o out.log -e err.log -c python web_demo.py --bind-address 0.0.0.0 --port 5000

forever start -c python web_demo.py --bind-address 0.0.0.0 --port 5000

python play_train_eval_zero.py \
--lagent bots/zeroagent_v2.hdf5 \
--ragent bots/zeroagent_v2.hdf5 \
-g 50 \
-d /home/ubuntu/git/AlphaGo-Zero-Compact/DLGo/bots \
-w 1 \
-b 9 \
--lr 0.01 \
--bs 256 \
-l log


I ran into the same issue after following this tutorial to install NodeJS.

I was able to get it work by installing a more recent NodeJS.

Follow these steps:

Uninstall NodeJS:
sudo apt purge nodejs
sudo apt autoremove
Install curl to download latest NodeJS setup:
sudo apt-get install curl
Check out https://nodejs.org/ to see what is the latest LTS version.
Download it:
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
(replace "12" with the current LTS major version number).
Install NodeJS (incl. npm):
sudo apt-get install nodejs
Install forever:
sudo npm install forever -g

"""

In [ ]:
"""
python init_zero_agent.py \
--board-size 9 \
bots/zero_testt.hdf5

python init_zero_agent_with_reg.py \
--board-size 9 \
bots/zerov3_test.hdf5

python init_zero_agent_v2.py \
--board-size 9 \
bots/zerov8_test.hdf5

python play_train_eval_zero.py \
--agent bots/zerov3_agent_cur.hdf5 \
-g 200 \
-d /Users/georgeyeh/DLGo/bots \
-w 1 \
-b 9 \
--lr 0.01 \
--bs 1024 \
-l zerov3log

python play_train_eval_zero.py \
--lagent bots/zeroagent_v1.hdf5 \
--ragent bots/zeroagent_v1.hdf5 \
-g 100 \
-d /Users/georgeyeh/gitproject/AlphaGo-Zero-Compact/DLGo/bots \
-w 1 \
-b 9 \
--lr 0.01 \
--bs 1024 \
-l log

npm install

forever start /Users/georgeyeh/deep_learning_and_the_game_of_go/code/gtp2ogs.js \
--username george99887654-bot \
--apikey 885fd89daebb3c971d77bd13d19f305bcf4e041f \
--hidden \
--persist \
--boardsizes 19 \
--debug -- run_gtp.py

node /Users/georgeyeh/deep_learning_and_the_game_of_go/code/gtp2ogs.js \
--apikey 885fd89daebb3c971d77bd13d19f305bcf4e041f \
--username george99887654-bot \
--hidden \
--persist \
--boardsizes 19 \
--debug -- run_gtp.py

PATH=/home/ubuntu/deep_learning_and_the_game_of_go/code:$PATH node gtp2ogs.js \
--username george99887654-bot \
--apikey 885fd89daebb3c971d77bd13d19f305bcf4e041f \
--hidden \
--persist \
--boardsize 19 \
--debug -- run_gtp_aws.py > log 2>&1 &
"""

In [ ]:
"""
python eval_zero.py \
--tagent bots/zero_agent_v5.hdf5 \
--ragent bots/zeroagent_v1.hdf5 \
-g 100 \
-d /Users/georgeyeh/gitproject/AlphaGo-Zero-Compact/DLGo/bots \
-w 1 \
-b 9 \
--lr 0.01 \
--bs 1024 \
-l evallog



python eval_zero.py \
--tagent bots/zero_agent_v3.hdf5 \
--ragent bots/zeroagent_v2.hdf5 \
-g 100 \
-d /home/ubuntu/git/AlphaGo-Zero-Compact/DLGo/bots \
-w 1 \
-b 9 \
--lr 0.01 \
--bs 1024 \
-l evallog

"""

In [63]:
import numpy as np

a=np.array(((1,2,3),(4,5,6),(7,8,9)))
b=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [56]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [65]:
b[,:,]=a[,,:]

SyntaxError: invalid syntax (<ipython-input-65-79535671e9b6>, line 1)

In [40]:
a[1,2]

TypeError: list indices must be integers or slices, not tuple

In [170]:
c=np.array([1,2,3,4,5])

In [174]:
cc = c.reshape((1,5))

In [176]:
d = c[:-1]

In [177]:
e = c[-1:]

In [178]:
d

array([1, 2, 3, 4])

In [179]:
e

array([5])

In [81]:
d.reshape((2,2))

array([[1, 2],
       [3, 4]])

In [162]:
a = np.arange(6).reshape((3, 2))

In [163]:
a.tolist()

[[0, 1], [2, 3], [4, 5]]

In [137]:
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [180]:
f=np.concatenate([d,e])

In [187]:
ff = f.reshape((1,5))

In [188]:
np.shape(ff)

(1, 5)

In [109]:
a==1

True

In [120]:
index = np.random.randint(8)

In [121]:
index

6

In [122]:
for i in range(8):
    print(i)

0
1
2
3
4
5
6
7


In [164]:
np.shape(a.tolist())

(3, 2)

In [152]:
g = [1,2,3,4,5]

AttributeError: 'list' object has no attribute 'reshape'

In [160]:
dd=np.array(a)

In [155]:
ee =np.array(g).reshape(5)

In [189]:
b = 3

In [190]:
a = b

In [191]:
a = a+1

In [192]:
a

4

In [193]:
b

3

In [5]:
import numpy as np
a = np.array([1 2 3 4])

SyntaxError: invalid syntax (<ipython-input-5-e59f2d697858>, line 2)

In [22]:
np.shape(np.array([1,2,3,4]).tolist())

(4,)

In [17]:
np.array([c for c in range(10)])/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [25]:
print(type(np.array([c for c in range(10)])))

<class 'numpy.ndarray'>
